### ISSUE TITLE
fetchDeviceId not working with very long list of devices

### ISSUE THREAD

**Issue by phfu** [samherve/esp8266-domoticz-zeroconf#1]
I have about 46 temperature devices on my Domoticz device list !
Due to my RFXCOM 433MHz receiver that gets every temperature device in the area :(

The fetchDeviceId functions is not responding : the returnd string is about 55032 chars, wich is probably too much for the RAM on th ESP8266.

I changed the json request  to add a filter only on the used devices by adding &used=true
Code :
 url += "/json.htm?type=devices&used=true&filter=temp";

Therefore I got less devices, and it works.
What do you think about it ?

By the way, @samherve,  thanks for this work, I really appreciate sharing !

**Comment by samherve** [comment]
Hi @phfu , thanks a lot for you feedback, it's really nice to know someone else could make use of this :)

As for your suggestion, I agree and will update the code this way. I had the same kind of issue with the limited memory resources of the ESP, and I think a more permanent fix would be to use another way to parse the JSON, using another streaming library possibly.

Did you also use the mDNS part by the way ? I got stuck during my tests at some point, due to a buggy  Wifi home router not handling mDNS messages correctly, were you able to make it work ?

**Comment by phfu** [comment]
Hi @samherve 
I tried the mDNS part with domoticz running on my Raspberry, but without success.
I got an answer from my Raspberry in the 
 if (answerName.indexOf(DOMOTICZ_SERVICE_NAME) >= 0)   test
but it never went in the other tests, as if the rrtype  is not correct.

I also tried another simple way by using the mdns.queryService instead, just to get the IP.
I got no answer on the esp8266, although my PC sees it.

I think I'll keep it there, as this is beyond my knowledge :(
Another solution could be asking the domoticz ip and port at WIFI AP Mode setup.
If I got any thurther, I'll let you know.

Regards from France
Philippe

**Comment by phfu** [comment]
Hi @samherve 
I finally got it working
Your code is great :)
The problem was the  domoticzPath, in the mDNS of the Raspberry and in the code.
I have no /domoticz path to add to the adress, and an empty string in the RPi mDNS was not working.
So I supressed the path text in the RPi and in the esp8266 code and it worked fine to get the right adresse.
See log
[Log.txt](https://github.com/samherve/esp8266-domoticz-zeroconf/files/1650239/Log.txt)

Thanks again & regards
Philippe
